### ISSUE TITLE
installation problem2: version `GOMP_5.0` not found

### ISSUE THREAD

**Issue by josegarciamanteiga** [dawe/schist#72]
Hi Dawe!,
I have a problem within my env. I have installed schist with your conda command and have:

scanpy                    1.10.2             pyhd8ed1ab_0    conda-forge
schist                    0.9.1              pyhd8ed1ab_1    conda-forge

The scanpy was already there at 1.10.2 and that's exactly the one I needed to run without problems scvelo and cellrank2.0, so I'd like to keep it if I may....

and 

libgomp                   14.1.0               h77fa898_1    conda-forge
graph-tool-base           2.59            py311h2a117df_0    conda-forge
torch                     2.0.1                    pypi_0    pypi

The error is this:

```
Traceback (most recent call last):
  File "/beegfs/scratch/ric.cosr/ric.tonon/TononG_2329_scRNAseq/analysis/scGET_analysis.py", line 217, in <module>
    import schist as scs
  File "/home/garciamanteiga.jose/.conda/envs/cellrank2.0/lib/python3.11/site-packages/schist/__init__.py", line 1, in <module>
    from . import inference
  File "/home/garciamanteiga.jose/.conda/envs/cellrank2.0/lib/python3.11/site-packages/schist/inference/__init__.py", line 1, in <module>
    from ._model import fit_model
  File "/home/garciamanteiga.jose/.conda/envs/cellrank2.0/lib/python3.11/site-packages/schist/inference/_model.py", line 11, in <module>
    from .._utils import get_graph_tool_from_adjacency
  File "/home/garciamanteiga.jose/.conda/envs/cellrank2.0/lib/python3.11/site-packages/schist/_utils/__init__.py", line 1, in <module>
    from ._tl_utils import *
  File "/home/garciamanteiga.jose/.conda/envs/cellrank2.0/lib/python3.11/site-packages/schist/_utils/_tl_utils.py", line 3, in <module>
    import graph_tool
  File "/home/garciamanteiga.jose/.conda/envs/cellrank2.0/lib/python3.11/site-packages/graph_tool/__init__.py", line 110, in <module>
    dl_import("from . import libgraph_tool_core as libcore")
  File "/home/garciamanteiga.jose/.conda/envs/cellrank2.0/lib/python3.11/site-packages/graph_tool/dl_import.py", line 44, in dl_import
    exec(import_expr, local_dict, global_dict)
  File "<string>", line 1, in <module>

ImportError: /home/garciamanteiga.jose/.conda/envs/cellrank2.0/lib/python3.11/site-packages/torch/lib/libgomp-a34b3233.so.1: version `GOMP_5.0' not found (required by /home/garciamanteiga.jose/.conda/envs/cellrank2.0/lib/python3.11/site-packages/graph_tool/libgraph_tool_core.so)

```

Could you help me with it?
Thanks
Jose

**Comment by dawe** [comment]
Hello @josegarciamanteiga, looking at the backtrace it's clear this is a problem related to `graph-tool`, not `schist`, so you may want to open an issue there. However, simply googling your error message I found this  https://github.com/conda-forge/graph-tool-feedstock/issues/120#issue-2244283848 which I think is relevant to your configuration/issue

**Comment by josegarciamanteiga** [comment]
Thanks Dawe!
This ``` conda install -c conda-forge --override-channels pytorch pytorch_geometric graph-tool ``` on my env made the trick. Indeed it was found on the message you linked from conda-forge/grap-tool-feedstock. 

Now ```import schist as sct``` does not throw any error.
I let this remain here as solved issue to help others finding this error when using schist.
Best
Jose
